hazelcast/cloud-docs

- docs/modules/ROOT/nav.adoc
The latest sidebar styles rely on the navigation file having a consistent structure with the other products.
> Reconfigure navigation to work with new styles

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/data-migration.adoc
> Add Data Migration docs

- antora-playbook-local.yml
- antora-playbook.yml
- docs/modules/ROOT/nav.adoc
- link-check-playbook.yml
Addressed [Jira ticket HZC-1294](https://hazelcast.atlassian.net/browse/HZC-1294)
> Provide links to code samples

- docs/modules/ROOT/pages/release-notes.adoc
This PR to add latest release notes
> BAU-216 Add release notes for 2.8.2 and 2.8.3

- docs/modules/ROOT/pages/support.adoc
to reflect updates in the support portal
> removing zendesk and replacing support links

- docs/modules/ROOT/pages/charts-and-stats.adoc
- docs/modules/ROOT/pages/dedicated-cluster.adoc
- docs/modules/ROOT/pages/release-notes.adoc
- docs/modules/ROOT/pages/scale-up-down.adoc
- docs/modules/ROOT/pages/serverless-cluster.adoc
Added/updated descriptions of Dedicated and Serverless with some design details.
> DOCS-178 Architecture Overview

- docs/modules/ROOT/pages/release-notes.adoc
Hi there,
Draft release notes based on the following: https://hazelcast.atlassian.net/projects/HZC/versions/10353/tab/release-report-all-issues
I'm still not entirely sure that all the bug fixes need to be included.
> DOCS-267_Go Live Release Notes

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/backup-and-restore.adoc
- docs/modules/ROOT/pages/create-serverless-cluster.adoc
- docs/modules/ROOT/pages/dedicated-cluster.adoc
- docs/modules/ROOT/pages/serverless-cluster.adoc
- docs/modules/ROOT/pages/stop-and-resume.adoc
> DOCS-303 Update Stop to Pause to match UI

- docs/modules/ROOT/pages/get-started.adoc
See https://hazelcast.slack.com/archives/C035HQET5/p1669037977255899
> Fixing __key types for clients when creating a mapping.

- docs/modules/ROOT/pages/get-started.adoc
- tutorials/modules/ROOT/pages/create-materialized-view-from-kafka.adoc
@Serdaro, would remind reviewing/testing just step 1. Moved this from a prerequisite to part of the tutorial.
> DOCS-333 Add details for installation of Hazelcast CLI

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/aws-vpc-peering.adoc
- docs/modules/ROOT/pages/azure-vnet-peering.adoc
- docs/modules/ROOT/pages/backup-and-restore.adoc
- docs/modules/ROOT/pages/charts-and-stats.adoc
- docs/modules/ROOT/pages/connect-to-cluster.adoc
- docs/modules/ROOT/pages/create-account.adoc
- docs/modules/ROOT/pages/create-serverless-cluster.adoc
- docs/modules/ROOT/pages/custom-classes-upload.adoc
- docs/modules/ROOT/pages/deleting-a-cluster.adoc
- docs/modules/ROOT/pages/developer.adoc
- docs/modules/ROOT/pages/download-logs.adoc
- docs/modules/ROOT/pages/gcp-vpc-peering.adoc
- docs/modules/ROOT/pages/get-started.adoc
- docs/modules/ROOT/pages/hazelcast-version.adoc
- docs/modules/ROOT/pages/ip-white-list.adoc
- docs/modules/ROOT/pages/management-center.adoc
- docs/modules/ROOT/pages/maploader-and-mapstore.adoc
- docs/modules/ROOT/pages/multi-factor-authentication.adoc
- docs/modules/ROOT/pages/payment-methods.adoc
- docs/modules/ROOT/pages/scale-up-down.adoc
- docs/modules/ROOT/pages/stop-and-resume.adoc
- docs/modules/ROOT/pages/teams-and-users.adoc
- docs/modules/ROOT/pages/wan-replication.adoc
- tutorials/modules/ROOT/pages/create-materialized-view-from-kafka.adoc
Reflect changes to in cluster navigation and removal of teams and roles. Also removes tags that add the Teams and Users page to the Learning Center.
> DOCS-343 New nav and removal of team roles

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/set-budget.adoc
Final content ready for approval.
> DOCS-344 Budget Tracking

- docs/modules/ROOT/pages/download-logs.adoc
> DOCS-368 Downloading logs on a resuming server

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/delete-account.adoc
Closes https://hazelcast.atlassian.net/browse/DOCS-456
> DOCS-456 Add Delete Account instructions

- docs/modules/ROOT/pages/create-serverless-cluster.adoc
- docs/modules/ROOT/pages/serverless-cluster.adoc
- docs/modules/ROOT/pages/stop-and-resume.adoc
Closes [DOCS-470](https://hazelcast.atlassian.net/browse/DOCS-470)
[DOCS-470]: https://hazelcast.atlassian.net/browse/DOCS-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOCS-470 Conditions for pausing a cluster

- docs/modules/ROOT/pages/release-notes.adoc
> DOCS-522 Added full link address

- docs/modules/ROOT/pages/tools.adoc
- Removed Beta flag
- Updated description of CLC to include current features
> DOCS-543 Updates for CLC GA

- docs/modules/ROOT/pages/get-started.adoc
Fixes https://github.com/hazelcast/cloud-docs/issues/110
> Update Get Started instruction ordering

- docs/modules/ROOT/pages/create-serverless-cluster.adoc
Fixes https://github.com/hazelcast/cloud-docs/issues/109
> Update Create Serverless Instructions

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/dedicated-cluster.adoc
- docs/modules/ROOT/pages/migrate-to-cloud.adoc
Update Dedicated description in line with yesterday's review & minor changes to migration page.
https://deploy-preview-107--xenodochial-spence-280948.netlify.app/cloud/migrate-to-cloud.html
https://deploy-preview-107--xenodochial-spence-280948.netlify.app/cloud/dedicated-cluster.html
> DOCS-560 Update Dedicated Description

- docs/modules/ROOT/pages/connect-to-cluster.adoc
- docs/modules/ROOT/pages/get-started.adoc
Only the following clients are now visible: Java, Python, .NET and CLI
> DOCS-593_Leave_Subset_of_Clients

- docs/modules/ROOT/pages/overview.adoc
Added redirect on docs homepage for support link.
> DOCS-596 Support link broken

- docs/modules/ROOT/pages/add-kafka-mapping.adoc
- docs/modules/ROOT/pages/add-postgres-mapping.adoc
- docs/modules/ROOT/pages/connector-wizard.adoc
- docs/modules/ROOT/pages/create-kafka-connection.adoc
- docs/modules/ROOT/pages/create-postgres-connection.adoc
- docs/modules/ROOT/pages/delete-kafka-connection.adoc
- docs/modules/ROOT/pages/delete-postgres-connection.adoc
- docs/modules/ROOT/pages/imap-connections.adoc
- docs/modules/ROOT/pages/kafka-connections.adoc
- docs/modules/ROOT/pages/postgres-connections.adoc
Removed 'Manage Data' tags as not in hazelcast-docs config.
> DOCS-586 Update Tags

- docs/modules/ROOT/pages/connector-wizard.adoc
- docs/modules/ROOT/pages/get-started.adoc
Fix broken links and add note about Trial
> DOCS-586 Fix links and Note added for Trial

- docs/modules/ROOT/pages/connector-wizard.adoc
Remove link to Java client docs
> DOCS-586 Remove incorrect link

- tutorials/modules/ROOT/pages/create-materialized-view-from-kafka.adoc
Update instructions to match Viridian UI
> DOCS-568_Update_Instructions_to_Match_UI

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/authorize-connections.adoc
- docs/modules/ROOT/pages/developer-guide.adoc
Addition of new section in navigation:
**Clients and Connectivity**
- Developer Guide
- Connectivity (instead of authorization)
- API Keys
See preview of navigation: https://deploy-preview-128--xenodochial-spence-280948.netlify.app/cloud/get-started.html
> DOCS-581_Clients_Section

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/connect-to-cluster.adoc
- docs/modules/ROOT/pages/connector-wizard.adoc
- docs/modules/ROOT/pages/developer-guide.adoc
- docs/modules/ROOT/pages/execute-sql-queries.adoc
Executing SQL queries via the SQL Browser.
> DOCS-610_SQL_Browser

- .github/workflows/validate.yml
- antora-playbook-local.yml
- antora-playbook.yml
- check-links-playbook.yml
- package.json
- robots.txt
* Was using old link checker
* Was lacking the linked SQL On Viridian repo
* No need to declare robots as an external file
* Upgraded the antora dependency versions.
> Tidying up configuration files.

- docs/modules/ROOT/pages/cluster-side-modules.adoc
- docs/modules/ROOT/pages/maploader-and-mapstore.adoc
Ensure that the descriptions do not infer that these features only ingest data.
Also extended the information for completeness.
> Update Maploader and Mapstore Descriptions
